# Generated by Django 4.0.7 on 2023-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='url-адрес')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
                'ordering': ('name',),
            },
        ),
    ]
