# Generated by Django 2.2 on 2023-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='статус'),
        ),
    ]
