# Generated by Django 2.2 on 2023-01-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_product', '0002_auto_20230118_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена экспресс доставки')),
                ('edge_for_free_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='порог бесплатной доставки')),
                ('common_delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена обычной доставки')),
                ('quantity_popular', models.PositiveIntegerField(default=8, verbose_name='количество популярных товаров на главной странице')),
                ('time_cache_product', models.PositiveIntegerField(default=1, verbose_name='через сколько дней кэшировать данные о продукте')),
                ('category_main_page', models.ManyToManyField(to='app_product.Category', verbose_name='категории для показа на главной странице (не больше 3)')),
                ('root_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_category', to='app_product.Category', verbose_name='корневая категория каталога')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
