# Generated by Django 2.2 on 2023-01-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, verbose_name='номер телефона')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='город')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('description', models.TextField(blank=True, verbose_name='краткое описание для футера')),
                ('express_delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена экспресс доставки')),
                ('edge_for_free_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='порог бесплатной доставки')),
                ('common_delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена обычной доставки')),
                ('quantity_popular', models.PositiveIntegerField(default=8, verbose_name='количество популярных товаров на главной странице')),
                ('time_cache_product', models.PositiveIntegerField(default=1, verbose_name='через сколько дней кэшировать данные о продукте')),
                ('category_main_page', models.ManyToManyField(to='app_product.Category', verbose_name='категории для показа на главной странице (максимум 3)')),
                ('root_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_category', to='app_product.Category', verbose_name='корневая категория каталога')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
