# Generated by Django 2.2 on 2023-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'настройки', 'verbose_name_plural': 'настройки'},
        ),
    ]
