# Generated by Django 2.2 on 2023-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_auto_20230124_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='category_main_page',
            field=models.ManyToManyField(to='app_product.Category', verbose_name='категории для показа на главной странице (максимум 3)'),
        ),
    ]
