# Generated by Django 4.0.7 on 2023-01-13 14:03

import app_users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png'), app_users.validators.avatar_size_validate]),
        ),
    ]
