# Generated by Django 2.2 on 2023-01-18 09:09

import app_product.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, db_index=True, upload_to='category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'], message='Ошибка загрузки: допускаются только файлы с расширением .png .svg'), app_product.validators.product_image_size_validate], verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'svg'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png .svg'), app_product.validators.product_image_size_validate], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'svg'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png .svg'), app_product.validators.product_image_size_validate], verbose_name='изображение'),
        ),
    ]
