# Generated by Django 4.0.7 on 2023-01-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='app_product.parametername', unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='parametername',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='характеристика'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='значение'),
        ),
    ]
