# Generated by Django 4.0.7 on 2023-01-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_parameter_parameter_alter_parametername_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='app_product.parametername', verbose_name='название'),
        ),
    ]
