# Generated by Django 4.0.7 on 2023-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_alter_parameter_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='product',
        ),
        migrations.AddField(
            model_name='parameter',
            name='product',
            field=models.ManyToManyField(to='app_product.product'),
        ),
    ]
