# Generated by Django 4.0.7 on 2023-01-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_remove_product_options_remove_parameter_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='product',
        ),
        migrations.AddField(
            model_name='parameter',
            name='products',
            field=models.ManyToManyField(blank=True, db_index=True, to='app_product.product', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, db_index=True, upload_to='category/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='category/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='доступен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='limited',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ограниченная серия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, verbose_name='остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата обновления'),
        ),
    ]
