# Generated by Django 4.0.7 on 2023-01-16 08:06

import app_product.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_alter_product_options_remove_parameter_product_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, db_index=True, upload_to='category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'], message='Ошибка загрузки: допускаются только файлы с расширением .png'), app_product.validators.product_image_size_validate], verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png'), app_product.validators.product_image_size_validate], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png'), app_product.validators.product_image_size_validate], verbose_name='изображение'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
